### ISSUE TITLE
Invalid authentication token. Production environment.

### ISSUE THREAD

**Issue by pashazel** [chrismccord/sync#133]
Good day!
Faced with the problem in the production environment.
Took an example from the repository chrismccord/sync_example and began to run as instructed.
Config sync.yml

```
# Faye
development:
  server: "http://localhost:9292/faye"
  adapter_javascript_url: "http://localhost:9292/faye/faye.js"
  auth_token: DEVELOPMENT_SECRET_TOKEN
  adapter: "Faye"
  async: true

production:
  server: "http://mysite.com/faye"
  adapter_javascript_url: "http://mysite.com/faye/faye.js"
  auth_token: "9wjreifdkdsvsdf"
  adapter: "Faye"
  async: false
```

When you run in development, there is no problem. 
In design mode, as soon as I add the new entry in the log displays the following:

```
[Faye::Server] Processing reply: {"channel":"/batch_publish","error":"Invalid authentication token","successful":false}
[Faye::Server] Passing through outgoing extensions: {"channel":"/batch_publish","error":"Invalid authentication token","successful":false}
[Faye::Server] Returning replies: [{"channel":"/batch_publish","error":"Invalid authentication token","successful":false}]
[Faye::RackAdapter] HTTP response: "[{\"channel\":\"/batch_publish\",\"error\":\"Invalid authentication token\",\"successful\":false}]"
```

I tried to change auth_token in sync.yml to the value of the file config/sekrets.yml secret_key_base did not help.
Already a lot of time spent on the solution, but the problem still happened. Maybe you have an idea? Thank you.
