### ISSUE TITLE
Sync.server and Sync.FAYE_HOST return different url?

### ISSUE THREAD

**Issue by rueian** [chrismccord/sync#158]
Hi, I have a problem when using this awesome gem with SSL.

I have the following sync.yml:

``` yml
development:
  server: "https://localhost:9292/faye"
  adapter_javascript_url: "https://localhost:9292/faye/faye.js"
  auth_token: "0d298317ed60334561d44d2fe27a1db5839708ff9ed16b78617961e756f17afc"
  adapter: "Faye"
  async: true
```

and I run the following command in rails console:

``` bash
irb(main):001:0> Sync.server
=>  "https://localhost:9292/faye"
```

the result is the same as my config file.

But when I run the following in my browser javascript console:

``` javascript
> Sync.FAYE_HOST
< "http://localhost:9292/faye"
```

the protocol of url becomes HTTP.

This difference result in that Faye client using ws, instead of wss, to communicate with Faye server.
But when using HTTPS protocol, it is not allowed communicating over ws.

I found the source code
https://github.com/chrismccord/sync/blob/master/app/assets/javascripts/sync.coffee.erb#L7

It looks like that javascript `Sync.FAYE_HOST` is rendered by Ruby `Sync.server` in the backend. I can't figure out why they will become different in practice.

Do I missing something? Or is there any mechanism to override my settings?

Thanks.
