### ISSUE TITLE
URL Configuration

### ISSUE THREAD

**Issue by g8d3** [chrismccord/sync#81]
Hi,

This is my config:

```
production:
  server: "http://public_ip:9292/faye"
  adapter_javascript_url: "http://public_ip:9292/faye/faye.js" 
  adapter: "Faye"
  auth_token: "secret"
  async: true
```

`public_ip` is my public IP address. And I am running `rackup sync.ru -E production`.

Why when I go to a page where I am using `sync`, I continue seeing:

![screen shot 2013-09-22 at 1 02 24 pm](https://f.cloud.github.com/assets/671721/1188053/2e282bf6-23b1-11e3-8c34-908aaa34e831.png)

Problem is that although everything works fine in my local, from other computer it fails because it tries to reach something related with Faye in localhost, when it should be `public_ip`.

Here are my model controller and view:

```
class Task < ActiveRecord::Base
  sync :all
end
```

```
class TasksController < InheritedResources::Base
  enable_sync
  ...
end
```

```
      tbody
        - collection.each do |resource|
          = sync partial: 'task_row', resource: resource
        = sync_new partial: 'task_row', resource: resource

```

I am not sure I am posting complete information here, let me know if anything more is needed.
