### ISSUE TITLE
Faye Server is getting Empty Messages

### ISSUE THREAD

**Issue by MhdSyrwan** [chrismccord/sync#84]
I've tested everything on localhost production mode, but on the real server i'm getting empty messages sent to Faye Server

My Config File:

``` yaml
production:
  server: "http://my_site:9292/faye"
  adapter_javascript_url: "http://my_site:9292/faye/faye.js"
  adapter: "Faye"
  auth_token: "........."
  async: true
```

Faye Log:

``` log
3-12-14T05:11:27.900505 #28761] DEBUG -- : [Faye::RackAdapter] Received message via HTTP POST: "{\"channel\":\"/batch_publish\",\"data\":[],\"ext\":{\"auth_token\":\"e4e57508ae84869c3b45123c106ab362dc45cb894c82e9a2a53a45702a98143a\"}}"
I, [2013-12-14T05:11:27.901036 #28761]  INFO -- : [Faye::Server] Processing messages: [{"channel":"/batch_publish","data":[],"ext":{"auth_token":"e4e57508ae84869c3b45123c106ab362dc45cb894c82e9a2a53a45702a98143a"}}] (local: false)
D, [2013-12-14T05:11:27.901288 #28761] DEBUG -- : [Faye::Server] Passing through incoming extensions: {"channel":"/batch_publish","data":[],"ext":{"auth_token":"e4e57508ae84869c3b45123c106ab362dc45cb894c82e9a2a53a45702a98143a"}}
```
